trigger:
  branches:
    include:
      - main # Trigger on changes to the 'main' branch

pool:
  name: "Default" # Use your self-hosted agent pool

stages:
  - stage: Build
    displayName: "Build the Application"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          # Install dependencies
          - script: npm install
            displayName: "Install Dependencies"

          # Build the app
          - script: npm run build
            displayName: "Build the React App"

          # Copy build output to the artifact staging directory
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)/dist"
              Contents: "**"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
            displayName: "Copy Build Output to Artifact Staging Directory"

          # Publish the build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
