trigger:
  branches:
    include:
      - main  # Trigger the pipeline when pushing to the 'main' branch

pr:
  none  # No pull request trigger needed for now

variables:
  buildConfiguration: 'Release'  # Define build configuration (Release by default)
  artifactName: 'task-app.zip'  # Define artifact name for the build output

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        pool:
          name: 'Default'  # Using self-hosted agent pool, make sure it's set up
          
        steps:
          # Step 1: Checkout the code from GitHub
          - task: Checkout@1
            displayName: 'Checkout Code'

          # Step 2: Set up Node.js environment
          - task: UseNode@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Set up Node.js'

          # Step 3: Install dependencies
          - script: |
              npm install
            displayName: 'Install dependencies'

          # Step 4: Run the build command (assuming a Node.js app)
          - script: |
              npm run build
            displayName: 'Build app'

          # Step 5: Run unit tests and generate code coverage report
          - script: |
              npm test -- --coverage
            displayName: 'Run unit tests with coverage'

          # Step 6: Publish build artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Default artifact staging directory
              ArtifactName: $(artifactName)
              publishLocation: 'Container'  # Store in the pipeline container
            displayName: 'Publish Build Artifacts'
